import {useEffect,useState} from 'react';
import {apiRequest} from '../utils/api';
export default function FacultyAssignments(){
 const [teachers,setTeachers]=useState([]),[sections,setSections]=useState([]),[teacherId,setTeacherId]=useState(''),[ids,setIds]=useState([]),[status,setStatus]=useState('Active'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const [t,s]=await Promise.all([apiRequest('/api/teachers'),apiRequest('/api/sections')]);setTeachers(t);setSections(s);const selected=t.find(v=>v._id===teacherId);if(selected){setIds(selected.sectionIds);setStatus(selected.status);}}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 const teacher=teachers.find(t=>t._id===teacherId);
 function choose(value){const t=teachers.find(t=>t._id===value);setTeacherId(value);setIds(t?.sectionIds||[]);setStatus(t?.status||'Active');setMessage('');}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await apiRequest(`/api/teachers/${teacherId}`,{method:'PATCH',body:JSON.stringify({status,sectionIds:ids})});await load();setMessage('Teacher access and assignments saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="learning-card learning-workspace"><h2>Faculty access & section assignments</h2><p>Each section can have multiple teachers. Grades and student counts follow these assignments. Inactive teachers lose access on their next request.</p>{error&&<p role="alert" className="learning-alert">{error}</p>}{message&&<p role="status">{message}</p>}<form className="learning-form" onSubmit={save}><label>Teacher<select value={teacherId} onChange={e=>choose(e.target.value)} required><option value="">Select a teacher</option>{teachers.map(t=><option key={t._id} value={t._id}>{t.name} · {t.status}</option>)}</select></label><button className="learning-button secondary" type="button" onClick={load}>Refresh teacher list</button>{teacher&&<><label>Account status<select value={status} onChange={e=>setStatus(e.target.value)}>{teacher.status==='Invited'?<option>Invited</option>:<option>Active</option>}<option>Inactive</option></select></label><fieldset><legend>Assigned sections</legend>{!sections.length?<p>Create a section first.</p>:sections.map(s=><label className="learning-check" key={s.id}><input type="checkbox" checked={ids.includes(s.id)} onChange={e=>setIds(e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/><span>{s.name} · {s.gradeLevel||'Grade unconfirmed'}</span></label>)}</fieldset><button className="learning-button" disabled={busy}>{busy?'Saving…':'Save access & assignments'}</button></>}</form></section>;
}
