import LearningEvidence from '../components/LearningEvidence';
import {useEffect,useState} from 'react';
import {Download,RefreshCw,CheckCircle,ClipboardList} from 'lucide-react';
import {apiRequest,apiFetch} from '../utils/api';
const TOPICS=['Phishing','Smishing','Vishing','Pretexting','Baiting'];
const pct=v=>v===null||v===undefined?'—':`${Math.round(v*100)}%`;
export default function LearningWorkspace({user,mode='diagnostics'}) {
 const head=user?.role==='super';
 const [sections,setSections]=useState([]),[section,setSection]=useState(''),[grade,setGrade]=useState('');
 const [data,setData]=useState(null),[notes,setNotes]=useState([]),[bounties,setBounties]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[message,setMessage]=useState('');
 const [studentId,setStudentId]=useState(''),[kind,setKind]=useState('review'),[topic,setTopic]=useState(TOPICS[0]),[note,setNote]=useState(''),[date,setDate]=useState(''),[outcome,setOutcome]=useState('Pending'),[bountyId,setBountyId]=useState('');
 const filters=new URLSearchParams({...section&&{sectionId:section},...grade&&{grade}}).toString();
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');setData(null);setStudentId('');
   Promise.all([apiRequest('/api/sections',{signal:abort.signal}),apiRequest(`/api/analytics?${filters}`,{signal:abort.signal}),apiRequest(`/api/interventions?${filters}`,{signal:abort.signal}),mode==='interventions'?apiRequest('/api/bounties',{signal:abort.signal}):Promise.resolve([])])
   .then(([s,d,n,b])=>{setSections(s);setData(d);setNotes(n);setBounties(b);})
   .catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();
 },[filters,revision,mode]);
 const students=data?.students||[];
 async function save(e) {e.preventDefault();setBusy(true);setError('');setMessage('');try{
   await apiRequest('/api/interventions',{method:'POST',body:JSON.stringify({studentId,kind,topic,note,scheduledDate:date,outcome,bountyId})});
   setNote('');setMessage('Action recorded. Student-confirmed mentoring outcomes are unchanged.');setRevision(v=>v+1);
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 async function update(id,value) {setBusy(true);setError('');try{await apiRequest(`/api/interventions/${id}`,{method:'PATCH',body:JSON.stringify({outcome:value})});setRevision(v=>v+1);setMessage('Outcome updated.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function download(format) {setBusy(true);setError('');try{
   const query=new URLSearchParams({...section&&{sectionId:section},...grade&&{grade},...studentId&&{studentId},format});
   const response=await apiFetch(`/api/reports/${studentId?'individual':'institutional'}?${query}`);
   if(!response.ok)throw new Error((await response.json()).error||'Export failed.');
   const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`LEVELBLUE-learning-report.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Report downloaded.');
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="dashboard learning-workspace">
  <div className="dash-page-intro"><span className="dash-eyebrow">{head?'SCHOOL INSIGHTS':'TEACHING & SUPPORT'}</span><h1>{mode==='reports'?'Learning reports':mode==='interventions'?'Reviews & remediation':head?'Institutional diagnostics':'Classroom diagnostics'}</h1><p>{mode==='reports'?'Export recorded learning evidence with clear coverage and limitations.':mode==='interventions'?'Document a review, plan classroom support, and record the outcome.':'Find learning needs using recorded BKT mastery. Below 40% indicates a need for support, not an exam failure.'}</p></div>
  <div className="learning-filters"><label>Grade<select value={grade} onChange={e=>{setGrade(e.target.value);setSection('');}}><option value="">All grades</option><option>Grade 11</option><option>Grade 12</option></select></label><label>Section<select value={section} onChange={e=>setSection(e.target.value)}><option value="">{head?'All school sections':'All assigned sections'}</option>{sections.filter(s=>!grade||s.gradeLevel===grade).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="learning-button secondary" onClick={()=>setRevision(v=>v+1)} disabled={loading||busy}><RefreshCw size={15}/>Refresh</button></div>
  {error&&<div className="learning-alert" role="alert">{error} <button onClick={()=>setRevision(v=>v+1)}>Retry loading</button></div>}{message&&<p role="status" className="learning-success"><CheckCircle size={16}/>{message}</p>}
  {loading?<div className="dash-empty" role="status">Loading authorized learning records…</div>:data&&<>
   <div className="learning-stats"><article><span>Learners in view</span><strong>{students.length}</strong></article><article><span>With recorded mastery</span><strong>{students.filter(s=>s.assessedTopics>0).length}</strong></article><article><span>Need topic support</span><strong>{students.filter(s=>s.failedTopics.length).length}</strong></article><article><span>Comparable assessment pairs</span><strong>{students.reduce((n,s)=>n+(s.gain!==null?1:0)+(s.evidence?.pairs.length||0),0)}</strong></article></div>
   {mode==='diagnostics'&&<>
    <section className="learning-card"><h2>Topic coverage & support</h2><div className="learning-topic-grid">{data.topics.map(t=><article key={t.topic}><h3>{t.topic}</h3><strong>{pct(t.mastery)}</strong><p>Mean recorded mastery</p><div className="learning-meter"><span style={{width:pct(t.mastery===null?0:t.mastery)}}/></div><p><b>{t.support} of {t.assessed}</b> assessed learners below 40% ({pct(t.supportProportion)})</p><small>{t.unassessed} unassessed</small></article>)}</div></section>
    {head&&<section className="learning-card"><h2>Grade & section comparisons</h2><div className="learning-table-wrap" tabIndex={0} aria-label="Scrollable grade and section comparison"><table className="learning-table"><thead><tr><th>Group</th>{TOPICS.map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{[...data.grades.map(g=>({name:g.grade,topics:g.topics})),...data.comparisons].map((g,i)=><tr key={i}><th>{g.name}</th>{g.topics.map(t=><td key={t.topic}>{pct(t.mastery)}<small>{t.assessed} assessed · {t.support} need support</small></td>)}</tr>)}</tbody></table></div></section>}
    <section className="learning-card"><h2>Student mastery heatmap</h2><p>— Unassessed · Under 40% needs support · 40–89% developing · 90%+ strong</p>{!students.length?<p className="dash-empty">No learners in this selection. Create a section or ask the school head to confirm your assignments.</p>:<div className="learning-table-wrap" tabIndex={0} aria-label="Scrollable student mastery heatmap"><table className="learning-table"><thead><tr><th>Student / section</th>{TOPICS.map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{students.map(s=><tr key={s._id}><th>{s.name}<small>{s.section||'Unassigned'}</small></th>{TOPICS.map(t=><td key={t}><span className={`mastery-cell ${s.mastery[t]===null?'unknown':s.mastery[t]<.4?'support':s.mastery[t]>=.9?'strong':'developing'}`}>{pct(s.mastery[t])}<small>{s.mastery[t]===null?'Unassessed':s.mastery[t]<.4?'Needs support':s.mastery[t]>=.9?'Strong':'Developing'}</small></span></td>)}</tr>)}</tbody></table></div>}</section>
   </>}
   {mode!=='interventions'&&<LearningEvidence key={filters} data={data}/>} 
   {mode==='interventions'&&<div className="learning-two-col"><section className="learning-card"><h2><ClipboardList size={18}/> Record an action</h2><form className="learning-form" onSubmit={save}><label>Student<select required value={studentId} onChange={e=>{setStudentId(e.target.value);setBountyId('');}}><option value="">Select a learner</option>{students.map(s=><option key={s._id} value={s._id}>{s.name} · {s.section}</option>)}</select></label><label>Action<select value={kind} onChange={e=>setKind(e.target.value)}><option value="review">Reviewed learning needs</option><option value="remediation">Direct classroom remediation</option><option value="bounty-review">Reviewed mentor bounty</option></select></label><label>Topic<select value={topic} onChange={e=>setTopic(e.target.value)}>{TOPICS.map(t=><option key={t}>{t}</option>)}</select></label>{kind==='bounty-review'&&<label>Bounty<select required value={bountyId} onChange={e=>setBountyId(e.target.value)}><option value="">Select a bounty</option>{bounties.filter(b=>String(b.mentee_id)===studentId).map(b=><option key={b.id} value={b.id}>{b.topic} · {b.status}{b.cancelled_at?' · Cancelled':''}</option>)}</select></label>}<label>Review or remediation note<textarea required maxLength={5000} rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Describe the learning need and your next step."/></label>{kind==='remediation'&&<label>Scheduled date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}<label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}>{['Pending','In progress','Completed','Follow-up needed'].map(v=><option key={v}>{v}</option>)}</select></label><button className="learning-button" disabled={busy||!students.length}>{busy?'Saving…':kind==='review'?'Mark reviewed':'Save action'}</button></form></section><section className="learning-card"><h2>Recorded actions</h2><p>Teacher review is separate from student confirmation of mentoring.</p>{!notes.length?<p className="dash-empty">No recorded action in this selection.</p>:notes.map(n=><article className="learning-note" key={n.id}><strong>{students.find(s=>String(s._id)===n.student_id)?.name||'Learner'} · {n.topic}</strong><small>{n.kind} · {new Date(n.created_at).toLocaleString()}</small><p>{n.note}</p>{n.scheduled_date&&<small>Scheduled: {n.scheduled_date}</small>}<label>Outcome<select disabled={busy} value={n.outcome} onChange={e=>update(n.id,e.target.value)}>{['Pending','In progress','Completed','Follow-up needed'].map(v=><option key={v}>{v}</option>)}</select></label></article>)}</section></div>}
   {mode==='reports'&&<section className="learning-card learning-report"><h2>Export learning evidence</h2><p>Includes scope, generation date, feedback response counts, assessment coverage, recorded scores, topic mastery and documented interventions.</p><label>Report scope<select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">{head?'Institutional report for the selected filters':'Select a student'}</option>{students.map(s=><option key={s._id} value={s._id}>{s.name} · {s.section}</option>)}</select></label><div className="learning-actions">{['pdf','csv'].map(format=><button className="learning-button" key={format} disabled={busy||(!head&&!studentId)} onClick={()=>download(format)}><Download size={16}/>{busy?'Preparing…':`Download ${format.toUpperCase()}`}</button>)}</div><p>Valid zero scores are retained. Gains are included only when both tests have confirmed completion and the same scale. This report presents evidence; it does not certify accreditation.</p></section>}
   <p className="dash-footnote">Missing learning records remain unavailable. Program completion requires an agreed curriculum; promotion and announcements are separate milestones.</p>
  </>}
 </div>;
}
